### PR TITLE
Added New Project : QR Code Generator

### PR DESCRIPTION
**Pull request by vivekthedev**
# Description
Added New Project
With README.md
With Images
Added Project to Index

- [ ] Issue_no: ```<insert your issue no here>```
- [x] Not applicable 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.

- [x] New project insert
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Project

- #### **Your Project Name: **QR Code Generator 

- #### **Short Description: ** Get QR Code of any text in a PNG image.

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/nduongthucanh/python-mini-project/blob/master/README_TEMPLATE.md)
- [x] My changes do not produce any warnings.

### CODE REVIEW

**Review by implosion07 — COMMENTED** [review]
please can you elaborate the description a little bit more for clarity

**Review by implosion07 — COMMENTED** [review]
please give a little more description inreadme.md about code

**Comment by vivekthedev** [comment]
> please give a little more description inreadme.md about code

Sure

**Comment by vivekthedev** [comment]
Added more description in the project readme

**Pull request closed without merging**
